### ISSUE TITLE
cutting off margins in rstudio

### ISSUE THREAD

**Issue by garthtarr** [garthtarr/pairsD3#5]
Hi Garth,

pairsD3 is truly great!

Q:
In Rstudio, this code:

``` r
pairsD3(iris[,1:4], group=iris[,5])
```

displays the 4X4 iris plot panels OK.

But...the rightmost 4 panels 
and some data points
are partially "cut off".
It looks like this:

![pairsd3_iris](https://cloud.githubusercontent.com/assets/2189134/17353329/f110f3b0-5981-11e6-8526-03287e789edd.png)

See? -------------------------------------^
The right margin line of the right 4 boxes is blank
and some of the data points there
are missing ...

Help, Garth!
RAY 

  Rstudio (latest version)
  R version 3.2.5
  Ubuntu Linux 12.04 LTS (32 bits)

**Comment by garthtarr** [comment]
Hi Ray,

Thanks for the positive feedback.  There are some formatting/margin issues that I haven't been able to resolve yet.  Your image didn't come through so I can't see exactly what you were pointing out.  But if you slide the viewer pane down a little it will shrink the right hand margin (to make sure everything remains square) or you can open it in a web browser and view it externally.

All the best,
Garth

**Comment by garthtarr** [comment]
Hi Garth,

Hey, thanks for that quick response!

Tried both your suggestions,
but rightmost margin still "cut-off".

Viewing as an external webpage: right margin still missing.
But :-)
if I export the plot as HTML it shows OK (no margins missing).

RAY

**Comment by garthtarr** [comment]
Hi Ray,

I think I will need to play around with the default padding parameters some more (and test it out in different operating systems).  There won't be a quick fix until I find a few hours to get my head back into the javascript that underpins the visualisation (I'm not a native javascript/D3 speaker)!

All the best,
Garth

**Comment by timelyportfolio** [comment]
I think it is an easy fix.  I'll submit a pull in a couple of minutes.

**Comment by garthtarr** [comment]
#6
