### ISSUE TITLE
Scatter plot of variables against themselves

### ISSUE THREAD

**Issue by nuno-agostinho** [garthtarr/pairsD3#7]
Hey there, @garthtarr, thank you for this lovely package.

I would like to ask an option to make the points in the diagonal plots visible.

By the way, the reason I know they are there is that you can drag in those plots which highlights the points in the other plots, like so:

![screen shot 2017-09-18 at 18 03 47](https://user-images.githubusercontent.com/3199157/30554232-c169a40a-9c9b-11e7-9e56-c45fd39da4d0.png)

Cheers,
Nuno Agostinho

**Comment by garthtarr** [comment]
Hi @nuno-agostinho I've updated so it now has the argument `diag` which can be `diag=TRUE` to plot the variables against each other or (the default) `diag=FALSE`

**Comment by nuno-agostinho** [comment]
Thanks, @garthtarr! 👍
